### ISSUE TITLE
What about `"up": "taze major -I"` changed to be "up": "taze latest -I"

### ISSUE THREAD

**Issue by LoTwT** [YunLeFun/vitesse-h5#3]
I think the `latest` seems to be better than `major` as the taze choice.

**Comment by YunYouJun** [comment]
You can use `pnpm up --latest -i`.

**Comment by antfu** [comment]
It's just a template after all. Feel free to change it on your own project, thanks.

**Comment by LoTwT** [comment]
`pnpm up` is the alias of [`pnpm upgrade`](https://pnpm.io/cli/update), so it needs to use `pnpm run up --latest`, and the taze mode will change. 

`major` and `latest` mode of taze seem to have the same behaviour, I will check the source code and close this issue.

Thanks.
