### ISSUE TITLE
[建议] 大佬这个作为模板使用的话，可以启用 github 的 Template repository 功能

### ISSUE THREAD

**Issue by zhengxs2018** [YunLeFun/vitesse-h5#5]
在设置里启用

![image](https://user-images.githubusercontent.com/7506913/185820975-0e51bcb9-910e-4b7b-8f46-8847b26893f9.png)

你的仓库就会出现 `Public template` 的标签，文件视图上方还会出现 `Use this template` 的按钮

![image](https://user-images.githubusercontent.com/7506913/185821342-47ff6fbe-c557-4717-a730-71ca40324368.png)

**Comment by zhengxs2018** [comment]
启用这个功能的好处是，不用 fork 就可以直接创建一个 github 仓库，否则需要先克隆到本地，修改完，再提交到新的 github 仓库

**Comment by YunYouJun** [comment]
Enabled.
