### ISSUE TITLE
Is it necessary to distinguish tsconfig between different envs such as node, web and test like create-vue?

### ISSUE THREAD

**Issue by LoTwT** [YunLeFun/vitesse-h5#8]

**Comment by YunYouJun** [comment]
Vitese-h5 is a pure front-end static template, and I don't think it will require a pure Node environment `tsconfig.json`.

**Comment by LoTwT** [comment]
Yes, it's a pure front-end static template. And I think it is strong enough for production.

But, sometimes, it will need a script to prepare source data like `scripts/convert` in Cook.

Also, some bigger projects which need better TS type support may need to inject the `process.env.VITE_XXX` property in `package.json`. The type annotation in `shims.d.ts` may confuse because it will not exist on the Web side.

I think it could be better if it had an independent `tsconfig.node.json`.

**Comment by YunYouJun** [comment]
You can use `import.meta.VITE_xxx` for it. Vite has supported it.

**Comment by YunYouJun** [comment]
There seems to be no necessary reason for us to do so.
If you have a development problem that must be solved, you can create another issue.
