### ISSUE TITLE
After update eslint to 8.40.0, it will be error when running "pnpm lint"

### ISSUE THREAD

**Issue by LoTwT** [YunLeFun/vitesse-h5#9]
repro steps:
- clone the repo
- pnpm update eslint
- pnpm lint

error:
<img width="1255" alt="image" src="https://github.com/YunLeFun/vitesse-h5/assets/50254496/02655d98-d8c6-44c5-a247-a5a2b245eeed">

sys info:

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.82 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/Library/Caches/fnm_multishells/2412_1684290901739/bin/node
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/2412_1684290901739/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 106.0.5
    Safari: 16.4
  npmPackages:
    vue: ^3.2.47 => 3.2.47

**Comment by YunYouJun** [comment]
Do not update eslint, the current version works well (see ci).

**Comment by LoTwT** [comment]
> Do not update eslint, the current version works well (see ci).

🤣 I just want to use `vue@3.3.2` and update deps fully by `pnpm dlx taze latest -I`. 

I have compared this repo with `antfu/vitesse`, `vitesse` runs well after updating `eslint@8.40.0`. But I can't find the reason.

**Comment by YunYouJun** [comment]
Did you upgarde `@antfu/eslint-config`? I remember earlier versions of it having compatibility issues with `eslint@8.40.0`.

**Comment by YunYouJun** [comment]
Now, i upgraded, and it works well.

**Comment by LoTwT** [comment]
> Now, i upgraded, and it works well.

Thanks!
